spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://database-1.ctlrxrcqpjop.us-east-1.rds.amazonaws.com:3306/profile
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        enable_lazy_load_no_trans: true
